# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables: # pipeline-level 
 branch: 'master'

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    git remote add github https://wwscthjm%40gmail.com:W3151953404wwscthjm@github.com/wwscthjm/Python.git
    git checkout -b $(branch)
    git push -u github $(branch)
  displayName: 'Run a multi-line script'
